export { HomeView } from "./home";
export { MyAccountView } from "./myaccount";
export {PoolManagementView} from "./pool-management/pool-management";
export {StakingManagementView} from "./platform-settings/platform-settings";
export {LiquidityView} from "./liquidity";
export {TradeView} from "./trade";
export {RedeemView} from "./redeem";
export {StakeView} from "./stake";
export {GovernanceView} from "./governance";
export {FarmingRewardsView} from "./farming_rewards";
export {ClaimNFTView} from "./claimNFT";
export {PlatformStatsView} from "./plaftform-stats";
